backend:
  name: github
  branch: main
  repo: ewjoachim/mathilde-website

publish_mode: editorial_workflow

media_folder: "content/img"
public_folder: "/img"

site_url: https://TODO.fr

collections:

  - name: metadata
    label: "Données du site"
    files:
    - label: "Métadonnées pour les moteurs de recherche et les réseaux sociaux"
      name: seo_metadata
      file: seo_metadata.yml
      fields:
        - {label: "Titre de l'onglet", name: "page_title", widget: "string"}
        - {label: "Description (pour les moteurs de recherche)", name: "description", widget: "string"}
        - {label: "Mots clés (pour les moteurs de recherche, séparé par des virgules)", name: "keywords", widget: "string"}
        - {label: "Image à afficher quand l'url est postée sur les réseaux sociaux", name: "social_image", widget: image}
    - label: "Contenu de la bannière et du pied de page"
      name: metadata
      file: metadata.yml
      fields:
        - {label: "Titre du site (bannière)", name: title, widget: "string"}
        - {label: "Titre du site (menu de navigation)", name: menu_title, widget: "string"}
        - {label: "Sous-titre", name: subtitle, widget: "markdown"}
        - {label: "Nom de domaine associé à l'email de contact", name: email_domain, widget: "string"}
        - {label: "URL de la page facebook", name: facebook_url, widget: "string"}
        - {label: "Contenu du footer (copyright etc)", name: copyright, widget: "markdown"}


  - name: "section" # Used in routes, e.g., /admin/collections/blog
    label: "Sections" # Used in the UI
    files:
      - label: "Qui suis-je ?"
        name: "about"
        file: "content/_about.md"
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Contenu
            name: body
            widget: markdown
          - name: images
            label: Images
            widget: list
            field:
              name: image
              label: Image
              widget: object
              fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}

      - label: "Prestations"
        name: "services"
        file: "content/_services.md"
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Contenu
            name: body
            widget: markdown
          - name: images
            label: Images
            widget: list
            field:
              name: image
              label: Image
              widget: object
              fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}

      - label: "Tarifs"
        name: "pricing"
        file: "content/_pricing.md"
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Contenu
            name: body
            widget: markdown
          - name: images
            label: Images
            widget: list
            field:
              name: image
              label: Image
              widget: object
              fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}

      - label: "Contact"
        name: "contact"
        file: "content/_contact.md"
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Contenu
            name: body
            widget: markdown

          - name: images
            label: Images
            widget: list
            field:
              name: image
              label: Image
              widget: object
              fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}
